# Generated by Django 5.2 on 2025-04-10 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(help_text='Add car license plate', max_length=200, unique=True, verbose_name='License_plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(help_text='Add car VIN code', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, message='Length has to be 17')], verbose_name='Vin_code'),
        ),
    ]
