# Generated by Django 5.2 on 2025-04-10 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_car_license_plate_alter_car_vin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(help_text='Add car VIN code', unique=True, validators=[django.core.validators.MinLengthValidator(17, message='Length has to be 17')], verbose_name='Vin_code'),
        ),
    ]
