# Generated by Django 5.2 on 2025-04-10 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_car_vin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(help_text='Add car VIN code', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, message='Length has to be 17')], verbose_name='Vin_code'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(help_text='Add quantity', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(help_text='Add autoservice price', verbose_name='Service_price'),
        ),
    ]
