# Generated by Django 5.2 on 2025-04-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_car_vin_code_alter_orderline_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car model', 'verbose_name_plural': 'Car models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Order line', 'verbose_name_plural': 'Order lines'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
