# Generated by Django 5.2 on 2025-04-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Administered'), ('t', 'Taken'), ('c', 'Ready'), ('b', 'Booked')], default='a', help_text='Status', max_length=1),
        ),
    ]
