# Generated by Django 5.2 on 2025-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_orderline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Administered'), ('t', 'Taken'), ('c', 'Ready'), ('b', 'Booked')], default='a', help_text='Status', max_length=1),
        ),
    ]
